In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv(r"C:\Users\Girish\Downloads\customer_churn_sample.csv")

print("Dataset loaded successfully!")
print(f"Rows: {df.shape[0]}")
print(f"Columns: {df.shape[1]}")

df.head()

Dataset loaded successfully!
Rows: 15
Columns: 11

,CustomerID,Gender,Age,TenureMonths,SubscriptionType,MonthlyCharges,TotalCharges,ContractType,SupportTickets,PaymentMethod,Churn
0,CUST-1001,Female,34,12,Basic,49.99,599.88,Month-to-Month,3,Credit Card,Yes
1,CUST-1002,Male,45,24,Pro,79.99,1919.76,One Year,1,Bank Transfer,No
2,CUST-1003,Female,29,6,Basic,49.99,299.94,Month-to-Month,5,UPI,Yes
3,CUST-1004,Male,52,36,Enterprise,149.99,5399.64,Two Year,0,Credit Card,No
4,CUST-1005,Female,41,8,Pro,79.99,639.92,Month-to-Month,4,Debit Card,Yes

In [3]:
print("=== DATASET SHAPE ===")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

print("\n=== COLUMN NAMES ===")
print(df.columns.tolist())

print("\n=== DATA TYPES ===")
print(df.dtypes)

print("\n=== DATASET INFORMATION ===")
df.info()

=== DATASET SHAPE ===
Rows: 15
Columns: 11

=== COLUMN NAMES ===
['CustomerID', 'Gender', 'Age', 'TenureMonths', 'SubscriptionType', 'MonthlyCharges', 'TotalCharges', 'ContractType', 'SupportTickets', 'PaymentMethod', 'Churn']

=== DATA TYPES ===
CustomerID           object
Gender               object
Age                   int64
TenureMonths          int64
SubscriptionType     object
MonthlyCharges      float64
TotalCharges        float64
ContractType         object
SupportTickets        int64
PaymentMethod        object
Churn                object
dtype: object

=== DATASET INFORMATION ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CustomerID        15 non-null     object
 1   Gender            15 non-null     object
 2   Age               15 non-null     int64
 3   TenureMonths      15 non-null     int64
 4   SubscriptionType  15 non-null     object
 5   MonthlyCharges    15 non-null     float64
 6   TotalCharges      15 non-null     float64
 7   ContractType      15 non-null     object
 8   SupportTickets    15 non-null     int64
 9   PaymentMethod     15 non-null     object
 10  Churn             15 non-null     object
dtypes: float64(2), int64(3), object(6)
memory usage: 1.4+ KB

In [4]:
print("=== MISSING VALUES ===")

missing_values = df.isnull().sum()

print(missing_values)

print("\nTotal missing values:",
      df.isnull().sum().sum())


print("\n=== DUPLICATE ROWS ===")

duplicate_rows = df.duplicated().sum()

print("Total duplicate rows:", duplicate_rows)

=== MISSING VALUES ===
CustomerID          0
Gender              0
Age                 0
TenureMonths        0
SubscriptionType    0
MonthlyCharges      0
TotalCharges        0
ContractType        0
SupportTickets      0
PaymentMethod       0
Churn               0
dtype: int64

Total missing values: 0

=== DUPLICATE ROWS ===
Total duplicate rows: 0

In [5]:
print("=== CATEGORICAL VALUE CHECK ===")

categorical_columns = df.select_dtypes(include="object").columns

for col in categorical_columns:
    print(f"\n{col}:")
    print(df[col].unique())

=== CATEGORICAL VALUE CHECK ===

CustomerID:
['CUST-1001' 'CUST-1002' 'CUST-1003' 'CUST-1004' 'CUST-1005' 'CUST-1006'
 'CUST-1007' 'CUST-1008' 'CUST-1009' 'CUST-1010' 'CUST-1011' 'CUST-1012'
 'CUST-1013' 'CUST-1014' 'CUST-1015']

Gender:
['Female' 'Male']

SubscriptionType:
['Basic' 'Pro' 'Enterprise']

ContractType:
['Month-to-Month' 'One Year' 'Two Year']

PaymentMethod:
['Credit Card' 'Bank Transfer' 'UPI' 'Debit Card']

Churn:
['Yes' 'No']

In [7]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

# Fix the CustomerID name to a clean format
df = df.rename(columns={"customerid": "customer_id"})

print("=== STANDARDIZED COLUMN NAMES ===")
print(df.columns.tolist())

=== STANDARDIZED COLUMN NAMES ===
['customer_id', 'gender', 'age', 'tenuremonths', 'subscriptiontype', 'monthlycharges', 'totalcharges', 'contracttype', 'supporttickets', 'paymentmethod', 'churn']

In [8]:
df = df.rename(columns={
    "tenuremonths": "tenure_months",
    "subscriptiontype": "subscription_type",
    "monthlycharges": "monthly_charges",
    "totalcharges": "total_charges",
    "contracttype": "contract_type",
    "supporttickets": "support_tickets",
    "paymentmethod": "payment_method"
})

print("=== FINAL COLUMN NAMES ===")
print(df.columns.tolist())

=== FINAL COLUMN NAMES ===
['customer_id', 'gender', 'age', 'tenure_months', 'subscription_type', 'monthly_charges', 'total_charges', 'contract_type', 'support_tickets', 'payment_method', 'churn']

In [9]:
numeric_columns = [
    "age",
    "tenure_months",
    "monthly_charges",
    "total_charges",
    "support_tickets"
]

print("=== NUMERICAL DATA TYPE VALIDATION ===")

for col in numeric_columns:
    print(f"{col}: {df[col].dtype}")

=== NUMERICAL DATA TYPE VALIDATION ===
age: int64
tenure_months: int64
monthly_charges: float64
total_charges: float64
support_tickets: int64

In [10]:
# Validate Customer ID structure

print("=== CUSTOMER ID VALIDATION ===")

# Check for missing Customer IDs
missing_ids = df["customer_id"].isnull().sum()
print("Missing Customer IDs:", missing_ids)

# Check for duplicate Customer IDs
duplicate_ids = df["customer_id"].duplicated().sum()
print("Duplicate Customer IDs:", duplicate_ids)

# Check Customer ID format
id_pattern = r"^CUST-\d{4}$"

invalid_ids = ~df["customer_id"].str.match(id_pattern, na=False)

print("Invalid Customer ID formats:", invalid_ids.sum())

=== CUSTOMER ID VALIDATION ===
Missing Customer IDs: 0
Duplicate Customer IDs: 0
Invalid Customer ID formats: 0

In [11]:
# Clean text and categorical columns

text_columns = df.select_dtypes(include="object").columns

for col in text_columns:
    df[col] = df[col].str.strip()

print("Text values cleaned successfully.")

Text values cleaned successfully.

In [12]:
print("========================================")
print("       FINAL DATASET VALIDATION")
print("========================================")

print("\nDataset shape:")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

print("\nMissing values:")
print(df.isnull().sum())

print("\nTotal missing values:",
      df.isnull().sum().sum())

print("\nDuplicate rows:",
      df.duplicated().sum())

print("\nData types:")
print(df.dtypes)

========================================
       FINAL DATASET VALIDATION
========================================

Dataset shape:
Rows: 15
Columns: 11

Missing values:
customer_id          0
gender               0
age                  0
tenure_months        0
subscription_type    0
monthly_charges      0
total_charges        0
contract_type        0
support_tickets      0
payment_method       0
churn                0
dtype: int64

Total missing values: 0

Duplicate rows: 0

Data types:
customer_id           object
gender                object
age                    int64
tenure_months          int64
subscription_type     object
monthly_charges      float64
total_charges        float64
contract_type         object
support_tickets        int64
payment_method        object
churn                 object
dtype: object

In [13]:
# Export the cleaned dataset

output_file = "cleaned_customer_churn.csv"

df.to_csv(output_file, index=False)

print("Cleaned dataset exported successfully!")
print("File name:", output_file)

Cleaned dataset exported successfully!
File name: cleaned_customer_churn.csv

In [14]:
print("=== FINAL CLEANED DATASET ===")

display(df.head())

print("\nFinal shape:", df.shape)

=== FINAL CLEANED DATASET ===

,customer_id,gender,age,tenure_months,subscription_type,monthly_charges,total_charges,contract_type,support_tickets,payment_method,churn
0,CUST-1001,Female,34,12,Basic,49.99,599.88,Month-to-Month,3,Credit Card,Yes
1,CUST-1002,Male,45,24,Pro,79.99,1919.76,One Year,1,Bank Transfer,No
2,CUST-1003,Female,29,6,Basic,49.99,299.94,Month-to-Month,5,UPI,Yes
3,CUST-1004,Male,52,36,Enterprise,149.99,5399.64,Two Year,0,Credit Card,No
4,CUST-1005,Female,41,8,Pro,79.99,639.92,Month-to-Month,4,Debit Card,Yes

Final shape: (15, 11)

In [15]:
import os

print("Exported file path:")
print(os.path.abspath("cleaned_customer_churn.csv"))

Exported file path:
C:\Users\Girish\cleaned_customer_churn.csv